language: r
cache: packages
r:
    - release

sudo: false

addons:
      apt:
          packages:
              - libgsl0-dev
                        
before_install:
    - #

script:
    - printf "starting testthat run\n"
    - Rscript -e "devtools::test()"
    - cd travisTest
    - cd ../tests
    - printf \"starting testthat run\\n\"
    - Rscript testthat.R
    