language: r
dist: trusty

r:
  - release

sudo: false

addons:
  apt:
    packages:
      - libgsl0-dev

r_packages:
  - devtools
  - testthat

script:
  #- Rscript .#build.R
  #- cd tests
  - printf "starting testthat run\n"
  #- Rscript testthat.R
  - Rscript -e "install.packages('Rcpp', repos = 'http://cran.us.r-project.org');Rcpp::compileAttributes()"
  - Rscript -e "devtools::install(local=FALSE);devtools::test()"
