language: r
dist: trusty

r:
  - release

sudo: false

addons:
  apt:
    packages:
      - libgsl0-dev

r_packages:
  - devtools
  - testthat

before_install:
  - R -e "devtools::install(".")"

script:
  - cd tests
  - printf "starting testthat run\n"
  - Rscript testthat.R