language: r
cache: packages
r:
    - release

sudo: false

addons:
      apt:
          packages:
              - libgsl0-dev
                        
before_install:
    - sudo R -e "install.packages(c('testthat'), repos = 'http://cran.rstudio.com/')"


script:
    - cd travisTest
    - printf "starting run\n"
    - Rscript test.R
    - cd ../tests
    - printf \"starting testthat run\\n\"
    - Rscript testthat.R
    