matrix:
  include:
  - language: r
    sudo: false
    cache: packages

    env:
      global:
        - WARNINGS_ARE_ERRORS=1

    r:
      - release

    addons:
      apt:
        packages:
          - libgsl0-dev

    r_packages:
      - devtools
      - testthat
      - Rcpp

    before_install:
      - cd R-Project

    script:
      - printf "Starting install and test with devtools.\n\n"
      - Rscript -e "Rcpp::compileAttributes()"
      - Rscript -e "install.packages('R-Project/', type = 'source', repos = NULL)"
      - Rscript -e "devtools::test()"
      - Rscript travisTest/test-on-prior-release.R
        ## The following won't work until we fix the ../../packedForest -> R-Project/src problem
        #- printf "Starting BUILD and CHECK --as-cran\n\n"
        #- R CMD build --resave-data .
        #- R CMD check --as-cran --no-manual rerf*tar.gz
  
  - language: cpp
    dist: xenial
    sudo: false
    compiler: 
      - gcc

    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6 

    before_install:
    - cd packedForest

    script:
      - make
      - cd test
      - make

  - language: python
    dist: xenial
    python: 
      - "3.6"
    before_install: cd Python
    install: 
      - pip install -r requirements.txt
      - pip install -e .
      - cd ..
    script:
      - pytest
    
