language: r
dist: trusty

r:
  - release

sudo: false

addons:
  apt:
    packages:
      - libgsl0-dev

r_packages:
  - devtools
  - testthat

script:
  - printf "Starting install and test with devtools.\n\n"
  - Rscript -e "devtools::install(local=FALSE);devtools::test()"
  - printf "Starting BUILD and CHECK --as-cran\n\n"
  - R CMD build --resave-data .
  - R CMD check --as-cran --no-manual rerf*tar.gz
