language: r
cache: packages
r:
  - release

sudo: false

addons:
  apt:
    packages:
      - libgsl0-dev

script:
  - cd tests
  - printf "starting testthat run\n"
  - Rscript testthat.R
  #- cd ../travisTest
  #- printf "starting run\n"
  #- Rscript test.R